import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "./Navbar";
import { Footer } from "../components/Footer";
import Navbar from "@/components/Navbar";
import WorkoutProvider from "@/context/WorkoutProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastContainer position="top-center" autoClose={3000} theme="dark" />
        <WorkoutProvider>
          <Navbar />
          {/* <main className="flex-1"> */}

          {children}
          {/* </main> */}

          <Footer />
        </WorkoutProvider>
      </body>
    </html>
  );
}
